version: '3'
services:
  cliff:
    image: clblount9/cliff-clavin
    ports:
      - '8080:8080'
  redis:
    image: redis
  delexis:
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      - ENVIRONMENT_TYPE=dockerCompose
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - AWS_REGION
      - AWS_PROFILE
      - AWS_BUCKET
      - JWT_SECRET
    build: ../../node-lexical-island/.
    ports:
      - '8081:8082'