apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: node-lexical-island-service
  name: node-lexical-island
spec:
  selector:
    matchLabels:
      app: node-lexical-island
  replicas: 2
  template:
    metadata:
      labels:
        app: node-lexical-island
    spec:
      containers:
      - image: clblount9/node-lexical-island
        name: node-lexical-island
        
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: backend-aws
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: backend-aws
              key: AWS_SECRET_ACCESS_KEY
        # Define the environment variable
        - name: REDIS_HOST # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: env-config         # The ConfigMap this value comes from.
              key: REDIS_HOST # The key to fetch.
        - name: REDIS_SEARCH_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: REDIS_SEARCH_HOST
        imagePullPolicy: Always          
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "200m"                
      restartPolicy: Always
