apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: clblount9/pink-percival:latest
        name: frontend
        env:
        # Define the environment variable
        - name: REDIS_HOST # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: env-config         # The ConfigMap this value comes from.
              key: REDIS_SEARCH_HOST # The key to fetch.
        - name: REDIS_SEARCH_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: REDIS_SEARCH_HOST
        imagePullPolicy: Always          
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always